[default]
check-filename = true

[default.extend-words]
encrypter = "encrypter"
requestor = "requestor"
Hashi = "Hashi"
KMS = "KMS"
kms = "kms"
Kms = "Kms"

[files]
extend-exclude = ["loadtest/scripts/http-rs.js"]
