[default]
check-filename = true
extend-ignore-re = [
  '\b[0-9a-f]{7,40}\b',
]

[default.extend-words]
encrypter = "encrypter"
requestor = "requestor"
Hashi = "Hashi"
kms = "kms"
9260ba2 = "9260ba2"

[files]
extend-exclude = ["loadtest/scripts/http-rs.js"]
