[log.console]
enabled = true
level = "DEBUG"
log_format = "default"

[server]
host = "127.0.0.1"
port = 3001

[limit]
request_count = 1
duration = 60

[database]
username = "db_user"
password = "db_pass"
host = "localhost"
port = 5432
dbname = "locker"

[cache]
tti = 7200 # i.e. 2 hours
max_capacity = 5000

[secrets]
locker_private_key = ""

[tenant_secrets]
public = { master_key = "feffe9928665731c6d6a8f9467308308feffe9928665731c6d6a8f9467308308", public_key = "", schema = "public" }

[external_key_manager]
mode = "disabled"

[redis]
host = "127.0.0.1"
port = 6379
pool_size = 5
reconnect_max_attempts = 0
reconnect_delay = 200
default_ttl = 300
default_hash_ttl = 900
use_legacy_version = false
stream_read_count = 1
auto_pipeline = true
broadcast_channel_capacity = 32
disable_auto_backpressure = false
max_in_flight_commands = 5000
default_command_timeout = 30
unresponsive_timeout = 10
unresponsive_check_interval = 2
max_feed_count = 200
max_failure_threshold_seconds = 5

[metrics]
mode = "disabled"

[runtime_config]
mode = "enabled"
ttl_seconds = 30
cache_max_capacity = 32

[runtime_config.endpoint]
base_url = "http://localhost:8080/configs"
api_key = ""
