[server]
host = "0.0.0.0"
port = 8080

[database]
url = "postgres://sam:damn@localhost/locker"

[secrets]
tenant = "hyperswitch"

locker_private_key = ""

[tenant_secrets]
hyperswitch = { master_key = "feffe9928665731c6d6a8f9467308308feffe9928665731c6d6a8f9467308308", public_key = "", schema = "public" }

[secrets_management]
secrets_manager = "no_encryption"

[secrets_management.aws_kms]
key_id = "us-west-2"
region = "abc"

[tls]
certificate = "cert.pem"
private_key = "key.pem"

[api_client]
client_idle_timeout = 90
pool_max_idle_per_host = 10
identity = ""

[external_key_manager]
url = "http://localhost:5000"
cert = ""
