//! Runtime configuration: a compile-time registry of per-tenant config entries.
//!
//! Every runtime config is declared exactly once, in the [`runtime_configs!`] invocation
//! below. That single declaration binds the config's `configs` row key to its Rust struct
//! and generates everything that depends on the pairing — the static-config seed field,
//! the [`RuntimeConfigEntry`] impl, the `POST /runtime-config` update variant and its
//! dispatch, plus seeding and status. Adding a config is one line; nothing else can be
//! forgotten, because nothing else is written by hand.

use std::{collections::HashMap, future::Future, time::Instant};

use hyperswitch_masking::PeekInterface;

use crate::{
    error::{self, ContainerError},
    storage::{self, ConfigInterface, KvConfigValues, consts},
};

#[derive(Debug, serde::Serialize)]
pub struct RuntimeConfigStatus {
    pub status: RuntimeConfigStatusKind,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub config: Option<serde_json::Value>,
}

#[derive(Debug, serde::Serialize)]
#[serde(rename_all = "snake_case")]
pub enum RuntimeConfigStatusKind {
    Disabled,
    NotConfigured,
    Available,
    Invalid,
}

/// One runtime config's `configs` row key, bound to its struct at compile time.
///
/// Implementations are generated by [`runtime_configs!`] — never write one by hand, or
/// the key and the struct can drift apart again.
pub trait RuntimeConfigEntry:
    serde::Serialize
    + serde::de::DeserializeOwned
    + Default
    + Clone
    + std::fmt::Debug
    + Send
    + Sync
    + Sized
{
    /// Primary key of this config's row in the `configs` table, and its Redis cache key
    /// (the per-tenant prefix is added by `TenantAwareRedisStore`).
    const KEY: &'static str;

    /// Checked against the currently persisted state before the new value is written.
    /// The default accepts anything that deserialized successfully.
    ///
    /// Desugared rather than written as `async fn` so the `Send` bound can be stated:
    /// the returned future is awaited inside axum handlers, which require it.
    fn validate(
        &self,
        _store: &storage::Storage,
        _manager: &RuntimeConfigManager,
    ) -> impl Future<Output = Result<(), ContainerError<error::RuntimeConfigError>>> + Send {
        async { Ok(()) }
    }
}

/// Declares every runtime config the binary knows about.
///
/// Grammar: `field: Type = "configs row key" [=> validator]`, where `validator` is an
/// `async fn(&Type, &Storage, &RuntimeConfigManager) -> Result<(), ContainerError<_>>`.
/// Omitting `=> validator` falls through to [`RuntimeConfigEntry::validate`]'s default.
///
/// Generates, per entry: a seed field on `RuntimeConfig::Enabled`, the
/// `RuntimeConfigEntry` impl, a [`RuntimeConfigUpdate`] variant tagged with the key, a
/// [`RuntimeConfigSeeds`] field, and the seed/dispatch arms. The update variant is named
/// after the type, so the declaration carries no redundant second name; the key stays a
/// literal because serde's `rename` cannot read an associated const.
macro_rules! runtime_configs {
    (
        $(
            $(#[$meta:meta])*
            $field:ident : $ty:ident = $key:literal $(=> $validator:path)?
        ),* $(,)?
    ) => {
        /// Runtime configuration source.
        ///
        /// When enabled, each runtime config lives in its own row of the per-tenant
        /// `configs` Postgres table, read through a per-tenant Redis cache. The values
        /// carried here are *seeds*: written at startup only when the row is absent
        /// (see [`RuntimeConfigManager::init`]), never used as a read-path fallback.
        /// The `admin_api_key` guards the `POST /runtime-config` update endpoint.
        #[derive(Debug, Clone, Default, serde::Deserialize)]
        #[serde(tag = "mode", rename_all = "snake_case")]
        pub enum RuntimeConfig {
            #[default]
            Disabled,
            Enabled {
                admin_api_key: hyperswitch_masking::Secret<String>,
                $(
                    $(#[$meta])*
                    #[serde(default)]
                    $field: $ty,
                )*
            },
        }

        $(
            impl RuntimeConfigEntry for $ty {
                const KEY: &'static str = $key;

                $(
                    fn validate(
                        &self,
                        store: &storage::Storage,
                        manager: &RuntimeConfigManager,
                    ) -> impl Future<
                        Output = Result<(), ContainerError<error::RuntimeConfigError>>,
                    > + Send {
                        $validator(self, store, manager)
                    }
                )?
            }
        )*

        /// Every registered config key, for operations that span all of them
        /// ([`RuntimeConfigManager::status`], cache warming).
        pub const REGISTERED_KEYS: &[&str] = &[$(<$ty as RuntimeConfigEntry>::KEY),*];

        /// Seed values lifted out of `RuntimeConfig::Enabled` so the manager can hold them.
        #[derive(Debug, Clone, Default)]
        pub struct RuntimeConfigSeeds {
            $(pub $field: $ty,)*
        }

        /// Body of `POST /runtime-config`: `{"key": "<key>", "value": {...}}`.
        ///
        /// serde performs the key → struct dispatch, so an unknown key and an unknown
        /// field inside `value` are both rejected before any storage call happens.
        #[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
        #[serde(tag = "key", content = "value", deny_unknown_fields)]
        pub enum RuntimeConfigUpdate {
            $(
                #[serde(rename = $key)]
                $ty($ty),
            )*
        }

        impl RuntimeConfigManager {
            /// Construct a manager from the global `RuntimeConfig` settings, capturing the
            /// configured seeds. Returns `None` when runtime config is disabled — a manager
            /// only exists when the feature is enabled, so its `admin_api_key` is always
            /// present. The owning tenant's `Storage` is passed to each method; the manager
            /// holds no storage handle of its own.
            pub fn new(config: &RuntimeConfig) -> Option<Self> {
                match config {
                    RuntimeConfig::Enabled { admin_api_key, $($field,)* } => Some(Self {
                        admin_api_key: admin_api_key.clone(),
                        seeds: RuntimeConfigSeeds { $($field: $field.clone(),)* },
                    }),
                    RuntimeConfig::Disabled => None,
                }
            }

            /// Seed every registered config whose row is missing.
            async fn seed_all(
                &self,
                store: &storage::Storage,
            ) -> Result<(), ContainerError<error::RuntimeConfigError>> {
                $(self.seed::<$ty>(store, &self.seeds.$field).await?;)*
                Ok(())
            }

            /// Apply an update: validate against the persisted state → PG upsert →
            /// Redis invalidate. The match is exhaustive over every registered config,
            /// so a new entry cannot be added without an update path.
            pub async fn update(
                &self,
                store: &storage::Storage,
                update: RuntimeConfigUpdate,
            ) -> Result<(), ContainerError<error::RuntimeConfigError>> {
                match update {
                    $(
                        RuntimeConfigUpdate::$ty(value) => {
                            value.validate(store, self).await?;
                            self.put(store, &value).await
                        }
                    )*
                }
            }
        }
    };
}

runtime_configs! {
    /// KV master switch and read-replica routing.
    kv_config: KvConfigValues = "kv_config" => validate_kv_config,

    // Add a runtime config by adding one line here. The seed field, the
    // `RuntimeConfigEntry` impl, the update variant, the update dispatch, seeding and
    // status all follow from this declaration — there is no second place to update.
}

impl RuntimeConfig {
    pub fn is_enabled(&self) -> bool {
        matches!(self, Self::Enabled { .. })
    }

    pub fn validate(&self) -> Result<(), crate::error::ConfigurationError> {
        if let Self::Enabled { admin_api_key, .. } = self
            && admin_api_key.peek().trim().is_empty()
        {
            return Err(
                crate::error::ConfigurationError::InvalidConfigurationValueError(
                    r#"runtime_config.admin_api_key is required when mode is "enabled""#.into(),
                ),
            );
        }

        Ok(())
    }
}

/// Manages runtime configuration backed by the per-tenant `configs` Postgres table with a
/// read-through per-tenant Redis cache.
///
/// No polling: every `get()` fetches the latest value from Redis (or Postgres on a cache
/// miss). `update()` upserts to Postgres and invalidates the Redis cache entry.
pub struct RuntimeConfigManager {
    admin_api_key: hyperswitch_masking::Secret<String>,
    seeds: RuntimeConfigSeeds,
}

impl RuntimeConfigManager {
    /// Bootstrap: ensure every registered config has a `configs` row (seeding from the
    /// static config when missing) and warm the Redis cache.
    ///
    /// Fails when a seed read or upsert errors — the tenant must not start serving with a
    /// missing runtime-config row. The Redis warm is best-effort only: a failed warm
    /// self-heals on the next read (read-through populate, TTL-bounded).
    pub async fn init(
        &self,
        store: &storage::Storage,
    ) -> Result<(), ContainerError<error::RuntimeConfigError>> {
        self.seed_all(store).await?;

        // Warm the Redis cache (read-through populates Redis on a miss).
        for key in REGISTERED_KEYS {
            let _ = self.get_raw(store, key).await;
        }

        Ok(())
    }

    /// Write the seed value when the config's row is absent, leaving an existing row
    /// untouched — an upgrade must never reset a tenant's live configuration.
    async fn seed<T: RuntimeConfigEntry>(
        &self,
        store: &storage::Storage,
        seed: &T,
    ) -> Result<(), ContainerError<error::RuntimeConfigError>> {
        let existing = store.find_config(T::KEY).await.inspect_err(|err| {
            crate::logger::error!(
                ?err,
                key = T::KEY,
                "Failed to read runtime config from Postgres during init"
            );
        })?;

        match existing {
            Some(_) => {
                crate::logger::debug!(key = T::KEY, "Runtime config already present in Postgres");
            }
            None => {
                let value = serde_json::to_value(seed).map_err(|err| {
                    ContainerError::from(error::RuntimeConfigError::InvalidValue(err.to_string()))
                })?;
                store.upsert_config(T::KEY, value).await.inspect(|_| {
                    crate::logger::info!(
                        key = T::KEY,
                        "Seeded configured runtime config into Postgres"
                    );
                })?;
            }
        }

        Ok(())
    }

    /// Persist a validated config value: PG upsert, then Redis invalidate.
    ///
    /// The Redis `DEL` failure is logged as a warning (not propagated) because the Redis
    /// TTL bounds staleness — the next read eventually repopulates from Postgres.
    async fn put<T: RuntimeConfigEntry>(
        &self,
        store: &storage::Storage,
        value: &T,
    ) -> Result<(), ContainerError<error::RuntimeConfigError>> {
        let json = serde_json::to_value(value).map_err(|err| {
            ContainerError::from(error::RuntimeConfigError::InvalidValue(err.to_string()))
        })?;

        store.upsert_config(T::KEY, json).await?;

        if let Some(redis) = store.get_redis_store() {
            redis.invalidate(T::KEY).await;
        }

        Ok(())
    }

    /// Deserialize the latest value of config `T`. The key comes from `T::KEY`, so a
    /// caller cannot pair a key with the wrong struct.
    ///
    /// Read-through: Redis GET → on hit, return immediately; on miss/error, fall back to
    /// Postgres SELECT and best-effort populate Redis. Returns `None` when no config row
    /// exists or both stores are unavailable (fail-closed: callers treat `None` as
    /// KV-disabled / replica-off).
    pub async fn get<T: RuntimeConfigEntry>(&self, store: &storage::Storage) -> Option<T> {
        let raw = self.get_raw(store, T::KEY).await?;

        match serde_json::from_str::<T>(&raw) {
            Ok(val) => Some(val),
            Err(error) => {
                crate::logger::error!(
                    ?error,
                    raw,
                    key = T::KEY,
                    "Failed to deserialize runtime config"
                );
                None
            }
        }
    }

    /// Fetch a config's raw JSON string, going through the read-through Redis cache.
    /// The only place a key is passed as a string rather than derived from a type —
    /// used by [`Self::status`], which reports on all keys uniformly.
    async fn get_raw(&self, store: &storage::Storage, key: &str) -> Option<String> {
        let start = Instant::now();
        let fetch_from_pg = || async {
            store
                .find_config(key)
                .await
                .inspect_err(|err| {
                    crate::logger::error!(
                        ?err,
                        key,
                        "Failed to read runtime config from Postgres"
                    );
                })
                .ok()
                .flatten()
                .map(|value| value.to_string())
        };

        let (source, result) = match store.get_redis_store() {
            Some(redis) => {
                let result = redis
                    .get_or_populate(key, consts::RUNTIME_CONFIG_REDIS_TTL_SECS, fetch_from_pg)
                    .await;
                ("redis", result)
            }
            None => {
                crate::logger::debug!(
                    key,
                    "Redis not configured, reading runtime config from Postgres"
                );
                ("postgres", fetch_from_pg().await)
            }
        };

        crate::observability::metrics::RUNTIME_CONFIG_FETCH_DURATION.record(
            start.elapsed().as_secs_f64(),
            metrics_utils::metric_attributes!(
                ("source", source),
                (
                    "outcome",
                    if result.is_some() { "success" } else { "error" }
                )
            ),
        );

        result
    }

    /// Reject illegal KV state transitions against the currently persisted state.
    ///
    /// `Disabled → Enabled` additionally requires a reachable Redis backend, since KV
    /// writes go through Redis.
    #[cfg(feature = "kv")]
    async fn validate_kv_transition(
        &self,
        store: &storage::Storage,
        requested: storage::kv::KvState,
    ) -> Result<(), ContainerError<error::RuntimeConfigError>> {
        use storage::kv::KvState;

        let current = self
            .get::<KvConfigValues>(store)
            .await
            .map(|values| values.enable_kv)
            .unwrap_or(KvState::Disabled);

        let can_enable_kv = match store.get_redis_store() {
            Some(redis) => redis
                .test()
                .await
                .inspect_err(|err| {
                    crate::logger::error!(
                        ?err,
                        "Redis health check failed while validating KV enablement"
                    );
                })
                .is_ok(),
            None => false,
        };

        if current.is_valid_transition(requested, can_enable_kv) {
            return Ok(());
        }

        crate::logger::warn!(
            current = %current,
            requested = %requested,
            "KV state transition rejected"
        );
        Err(ContainerError::from(
            error::RuntimeConfigError::InvalidStateTransition(format!("{current} -> {requested}")),
        ))
    }

    /// Reject enabling replica reads when no replica pool is configured or the replica
    /// is unreachable. Mirrors the previous global-state refresh behaviour, enforced at
    /// the only write path now (no in-process state to consult).
    async fn validate_replica_enablement(
        &self,
        store: &storage::Storage,
        requested_use_replica: bool,
    ) -> Result<(), ContainerError<error::RuntimeConfigError>> {
        if !requested_use_replica {
            return Ok(());
        }

        if !store.has_replica() {
            return Err(ContainerError::from(
                error::RuntimeConfigError::NoReplicaConfigured,
            ));
        }

        store.get_replica_conn().await.map(|_| ()).map_err(|err| {
            crate::logger::error!(
                ?err,
                "Replica health check failed while validating use_replica"
            );
            ContainerError::from(error::RuntimeConfigError::ReplicaUnreachable)
        })
    }

    /// Returns the current status of every registered runtime config, keyed by its
    /// config key, without side effects.
    pub async fn status(
        &self,
        store: &storage::Storage,
    ) -> HashMap<&'static str, RuntimeConfigStatus> {
        let mut statuses = HashMap::with_capacity(REGISTERED_KEYS.len());

        for key in REGISTERED_KEYS {
            let status = match self.get_raw(store, key).await {
                None => RuntimeConfigStatus {
                    status: RuntimeConfigStatusKind::NotConfigured,
                    config: None,
                },
                Some(raw) => match serde_json::from_str::<serde_json::Value>(&raw) {
                    Ok(config) => RuntimeConfigStatus {
                        status: RuntimeConfigStatusKind::Available,
                        config: Some(config),
                    },
                    Err(error) => {
                        crate::logger::error!(?error, raw, key, "Runtime config is invalid");
                        RuntimeConfigStatus {
                            status: RuntimeConfigStatusKind::Invalid,
                            config: None,
                        }
                    }
                },
            };

            statuses.insert(*key, status);
        }

        statuses
    }

    /// Constant-time comparison of a candidate API key against the configured admin key.
    pub fn verify_admin_api_key(&self, candidate: &str) -> bool {
        let expected_bytes = self.admin_api_key.peek().as_bytes();
        let candidate_bytes = candidate.as_bytes();
        constant_time_eq(expected_bytes, candidate_bytes)
    }
}

/// Status map reported when runtime config is disabled for a tenant: every registered
/// config reports `disabled`, so the response shape does not depend on the mode.
pub fn disabled_status() -> HashMap<&'static str, RuntimeConfigStatus> {
    REGISTERED_KEYS
        .iter()
        .map(|key| {
            (
                *key,
                RuntimeConfigStatus {
                    status: RuntimeConfigStatusKind::Disabled,
                    config: None,
                },
            )
        })
        .collect()
}

/// Validation for [`KvConfigValues`], wired in by the `runtime_configs!` declaration.
async fn validate_kv_config(
    value: &KvConfigValues,
    store: &storage::Storage,
    manager: &RuntimeConfigManager,
) -> Result<(), ContainerError<error::RuntimeConfigError>> {
    #[cfg(feature = "kv")]
    manager
        .validate_kv_transition(store, value.enable_kv)
        .await?;

    manager
        .validate_replica_enablement(store, value.use_replica)
        .await
}

fn constant_time_eq(a: &[u8], b: &[u8]) -> bool {
    if a.len() != b.len() {
        return false;
    }
    let mut diff = 0u8;
    for (x, y) in a.iter().zip(b.iter()) {
        diff |= x ^ y;
    }
    diff == 0
}

#[cfg(test)]
mod tests {
    use super::{REGISTERED_KEYS, RuntimeConfigEntry, RuntimeConfigUpdate};
    use crate::storage::KvConfigValues;

    /// Round-trip a request body and read one field back out, without unwrapping —
    /// `expect`/`panic` are clippy-warned crate-wide, tests included.
    fn field(body: &str, name: &str) -> Option<serde_json::Value> {
        serde_json::from_str::<RuntimeConfigUpdate>(body)
            .ok()
            .and_then(|update| serde_json::to_value(update).ok())
            .map(|json| json["value"][name].clone())
    }

    /// The declared key must be the serde tag, the `configs` row key and the Redis key
    /// all at once — every consumer depends on those being the same string.
    #[test]
    fn update_tag_matches_entry_key() {
        let tag = serde_json::to_value(RuntimeConfigUpdate::KvConfigValues(
            KvConfigValues::default(),
        ))
        .ok()
        .map(|json| json["key"].clone());

        assert_eq!(tag, Some(serde_json::Value::from(KvConfigValues::KEY)));
        assert!(REGISTERED_KEYS.contains(&KvConfigValues::KEY));
    }

    #[test]
    fn deserializes_tagged_body() {
        assert_eq!(
            field(
                r#"{"key":"kv_config","value":{"use_replica":true}}"#,
                "use_replica"
            ),
            Some(serde_json::Value::Bool(true))
        );
    }

    #[test]
    fn rejects_unknown_key() {
        assert!(
            serde_json::from_str::<RuntimeConfigUpdate>(
                r#"{"key":"not_a_registered_config","value":{"use_replica":true}}"#,
            )
            .is_err(),
            "an unknown config key must be rejected"
        );
    }

    #[test]
    fn rejects_unknown_field_in_value() {
        assert!(
            serde_json::from_str::<RuntimeConfigUpdate>(
                r#"{"key":"kv_config","value":{"use_replica":true,"not_a_field":1}}"#,
            )
            .is_err(),
            "an unknown field inside value must be rejected, not silently dropped"
        );
    }

    #[test]
    fn rejects_unknown_top_level_field() {
        assert!(
            serde_json::from_str::<RuntimeConfigUpdate>(
                r#"{"key":"kv_config","value":{},"extra":true}"#,
            )
            .is_err(),
            "an unknown top-level field must be rejected"
        );
    }

    #[cfg(feature = "kv")]
    #[test]
    fn deserializes_kv_state() {
        assert_eq!(
            field(
                r#"{"key":"kv_config","value":{"use_replica":false,"enable_kv":"soft_kill"}}"#,
                "enable_kv"
            ),
            Some(serde_json::Value::from("soft_kill"))
        );
    }
}

/// Seeds must survive both config sources. `RuntimeConfig` is an internally tagged enum
/// and the seed is a nested struct inside one of its variants — a combination the
/// `config` crate handles differently per source, so both are exercised here.
#[cfg(test)]
mod config_source_tests {
    use super::RuntimeConfig;
    use crate::storage::KvConfigValues;

    #[derive(serde::Deserialize)]
    struct TestDeser {
        runtime_config: RuntimeConfig,
    }

    fn seed_of(builder: config::ConfigBuilder<config::builder::DefaultState>) -> Option<KvConfigValues> {
        match builder.build().ok()?.try_deserialize::<TestDeser>().ok()? {
            TestDeser {
                runtime_config: RuntimeConfig::Enabled { kv_config, .. },
            } => Some(kv_config),
            _ => None,
        }
    }

    #[test]
    fn seed_loads_from_toml() {
        let data = r#"
        [runtime_config]
        mode = "enabled"
        admin_api_key = "test_key"

        [runtime_config.kv_config]
        use_replica = true
        "#;

        let seed = seed_of(
            config::Config::builder()
                .add_source(config::File::from_str(data, config::FileFormat::Toml)),
        );

        assert_eq!(seed.map(|values| values.use_replica), Some(true));
    }

    /// The env source is injected rather than set on the process: `std::env::set_var` is
    /// `unsafe` in edition 2024 and this crate forbids `unsafe_code`.
    #[test]
    fn seed_loads_from_env() {
        let env = std::collections::HashMap::from([
            ("LOCKER__RUNTIME_CONFIG__MODE".to_string(), "enabled".to_string()),
            (
                "LOCKER__RUNTIME_CONFIG__ADMIN_API_KEY".to_string(),
                "test_key".to_string(),
            ),
            (
                "LOCKER__RUNTIME_CONFIG__KV_CONFIG__USE_REPLICA".to_string(),
                "true".to_string(),
            ),
        ]);

        let seed = seed_of(
            config::Config::builder().add_source(
                config::Environment::with_prefix("LOCKER")
                    .separator("__")
                    .try_parsing(true)
                    .source(Some(env)),
            ),
        );

        assert_eq!(seed.map(|values| values.use_replica), Some(true));
    }

    /// An omitted seed section must still parse — existing deployments have no
    /// `[runtime_config.kv_config]` — and fall back to the struct default.
    #[test]
    fn seed_defaults_when_absent() {
        let data = r#"
        [runtime_config]
        mode = "enabled"
        admin_api_key = "test_key"
        "#;

        let seed = seed_of(
            config::Config::builder()
                .add_source(config::File::from_str(data, config::FileFormat::Toml)),
        );

        assert_eq!(seed.map(|values| values.use_replica), Some(false));
    }

    #[cfg(feature = "kv")]
    #[test]
    fn kv_state_seed_loads_from_toml() {
        use crate::storage::kv::KvState;

        let data = r#"
        [runtime_config]
        mode = "enabled"
        admin_api_key = "test_key"

        [runtime_config.kv_config]
        enable_kv = "soft_kill"
        "#;

        let seed = seed_of(
            config::Config::builder()
                .add_source(config::File::from_str(data, config::FileFormat::Toml)),
        );

        assert_eq!(seed.map(|values| values.enable_kv), Some(KvState::SoftKill));
    }
}
