name: CI

on:
  push:
    branches:
      - main

  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize

jobs:
  formatting:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt

      - name: Check formatting
        shell: bash
        run: cargo +nightly fmt --all --check

  test:
    name: Run tests on stable toolchain
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install mold linker
        uses: rui314/setup-mold@v1
        if: ${{ runner.os == 'Linux' }}
        with:
          make-default: true

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable 2 weeks ago
          components: clippy

      - name: Install cargo-hack
        uses: baptiste0928/cargo-install@v2.2.0
        with:
          crate: cargo-hack

      - uses: Swatinem/rust-cache@v2.7.0
        with:
          save-if: ${{ github.event_name == 'push' }}

      - name: Deny warnings
        shell: bash
        run: sed -i 's/rustflags = \[/rustflags = \[\n    "-Dwarnings",/' .cargo/config.toml

      - name: Run clippy
        shell: bash
        run: cargo clippy --all-features --all-targets

      - name: Cargo hack
        if: ${{ github.event_name == 'push' }}
        shell: bash
        run: cargo hack check --each-feature --no-dev-deps

  typos:
    name: Spell check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Spell check
        uses: crate-ci/typos@master
